### ISSUE TITLE
Cookie is invalid

### ISSUE THREAD

**Issue by Gabriele007xx** [Richard-Weiss/Bing-Creator-Image-Downloader#23]
I have trouble downloading the images as it seems my _U cookie is invalid. It says it couldn't find any collection with the given cookie. I am pretty sure it is (I went to a collection, went on inspect, went on Network tab and then on the cookie section, I used edge). I don't know if I can post my _U cookie here (I think i already did). Other things like the .env file, and requirements.txt are fine and the array is empty in the config.toml file ("[]").

**Comment by Richard-Weiss** [comment]
@Gabriele007xx
You thankfully didn't post your _U cookie anywhere in the repo.  
It's like an API token, so anyone using it could impersonate you. It's a secret.  
You can also try the method from this [repo](https://pypi.org/project/sydney-py/).
Also make sure the .env looks like this (this cookie is generated randomly using the same scheme and doesn't work):
`COOKIE=_U=FV3rABbRD686SNU6L0w6PDCjp4VA_rrgEPCDTgCtevG5JrTYBd87Lkuh8d467zzc5AFBRH41cMxqDaF_5ZH3Y86a2v15rE97vq636V4NZANn4P_ZNt0xcqAb9RcVQTayXP9HPmN7_yhnHbWrSt5ZHPXU2NNWMKaXJTGt8w7B5_J2ZGUVcx8hbBLZr4LCL1MYk7HQmBU2wNWUnzarN7y3t1H;`  
Also make sure the cookie is actually for the account that has the collection, if you have more than one account.

**Comment by HighDruidMotas** [comment]
Starting today, I'm also having this same issue. Used it successfully yesterday, nothing changed in config or .env
I've double-checked everything is correct, and have even started fresh with the repo.


C:\Users\IBuyPower\Desktop\Bing-Creator-Image-Downloader-main>python ./main.py
2023-12-31 11:43:12,257 INFO Fetching metadata of collections...
Traceback (most recent call last):
  File "C:\Users\IBuyPower\Desktop\Bing-Creator-Image-Downloader-main\main.py", line 631, in <module>
    asyncio.run(main())
  File "C:\Users\IBuyPower\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IBuyPower\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IBuyPower\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\IBuyPower\Desktop\Bing-Creator-Image-Downloader-main\main.py", line 561, in main
    await image_download.run()
  File "C:\Users\IBuyPower\Desktop\Bing-Creator-Image-Downloader-main\main.py", line 79, in run
    self.__images = self.__gather_image_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IBuyPower\Desktop\Bing-Creator-Image-Downloader-main\main.py", line 110, in __gather_image_data
    raise Exception('No collections were found for the given cookie.')
Exception: No collections were found for the given cookie.


Not sure if something was changed on Bing's end since yesterday (12/30) like cookie format, url, etc.

**Comment by Richard-Weiss** [comment]
@HighDruidMotas Cookies aren't meant to last forever. Have you tried using a fresh cookie?

**Comment by HighDruidMotas** [comment]
@Richard-Weiss yes
from multiple accounts

**Comment by Richard-Weiss** [comment]
@HighDruidMotas Make sure it's from the right account and try the steps from the other repo.  
You can theoretically paste the whole cookie value from that request, but the `_U` cookie is sufficient.

**Comment by HighDruidMotas** [comment]
@Richard-Weiss 
The correct _U cookie is being used for the correct account.
Same error.

**Comment by Richard-Weiss** [comment]
@HighDruidMotas I just tried it with another account and pasted the whole cookie value from the request and it works.  
Please try the steps describe in the `Prerequisites` section of this [repo](https://pypi.org/project/sydney-py/).  
I can help you if you have difficulties with any step.

**Comment by HighDruidMotas** [comment]
@Richard-Weiss I just did that, and got the same error, but will do it again I guess..

**Comment by HighDruidMotas** [comment]
@Richard-Weiss Same error using the other repo's method

**Comment by HighDruidMotas** [comment]
Will delete repo and start fresh again

**Comment by Richard-Weiss** [comment]
@HighDruidMotas 
There are only 4 reasons why that error might occur:
1. The cookie is invalid
2. The cookie value was not loaded into the environment variables
3. The associated account has no collections
4. The API is returning a 200 but not returning any collection for an unknown reason

Not sure what else I could suggest to you. I can't replicate this error across the 4 accounts I have.
Can you maybe try adding the line `print(os.getenv('COOKIE'))` after the line `load_dotenv()`?  
Be sure **not** to share the output with me though, as it's a secret.  
Just compare it with the value in the config file.
Deleting the repo will probably not help at this point.

**Comment by HighDruidMotas** [comment]
@Richard-Weiss Doesn't appear to be printing anything to collection_dict_dump_debug or bing_image_creator logs

**Comment by Richard-Weiss** [comment]
@HighDruidMotas I know, I thought about adding more debug information anyways.
I'll add some for this case.

**Comment by Richard-Weiss** [comment]
@HighDruidMotas I've added a statement for it now.  
Be sure to enable the debug mode again, it wasn't supposed to be on by default.

**Comment by HighDruidMotas** [comment]
@Richard-Weiss Okay, not sure how or why, but it seems like the cookie was not being seen/read in the .env file
had to actually recreate a new .env from the example file
worked with my test account, will now run it on the main account.

Thank you for the time and effort to troubleshoot!
